### PR TITLE
added password_toggle

### PR DESCRIPTION
**Pull request by rakshitkamboj**
I have successfully added a button in login_screen that will allow user to show/hide their password.

### CODE REVIEW

**Comment by pratyushmp** [comment]
@rakshitkamboj Can you also add the toggle to the Sign Up Screen

**Comment by rakshitkamboj** [comment]
@pratyushmp Yeah I will do it.
I have to do it for both password & confirm password form right?

**Comment by pratyushmp** [comment]
Yup

**Comment by rakshitkamboj** [comment]
@pratyushmp it's done.
Kindly review it.

**Review by pratyushmp — APPROVED** [review]

**Comment by rakshitkamboj** [comment]
@pratyushmp Can you please add GSSoC tag and also level tag to this issue.

**Pull request merged**
