### PR TITLE
Issue 68

### LINKED ISSUE #68: Navigate First Time users to user_details_screen.dart and store the details in firebase

### PR DESCRIPTION
**Pull request by Borahb**
# Description :

Added Navigation for first-time users to user details screen and store data in firestore.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/pratyushmp/Batua/blob/main/Contributing.md)?

- [x] Yes
- [ ] No

## Type of change :

_Please delete/edit options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist :

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by SapinderSingh** [comment]
@Borahb Why did you edited the create goal page ?

**Comment by Borahb** [comment]
@SapinderSingh Because it was showing a problem, so I thought of removing it.

**Comment by Borahb** [comment]
@SapinderSingh  Thanks for showing up the change in initial route part. I made the necessary changes.

**Comment by SapinderSingh** [comment]
> @SapinderSingh Thanks for showing up the change in initial route part. I made the necessary changes.

you should also restore changes in create goal page, because getting the month is required behavior

**Comment by Borahb** [comment]
@SapinderSingh  Okay, made the changes.

**Review by infiniteoverflow — APPROVED** [review]

**Pull request merged**
