### PR TITLE
Added proper structuring of files inside lib 

### PR DESCRIPTION
**Pull request by Borahb**
# Description :
Done proper structuring of files inside lib folder.
@pratyushmp 
Screenshot (464)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/pratyushmp/Batua/blob/main/Contributing.md)?

- [x] Yes
- [ ] No

## Type of change :

_Please delete/edit options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist :

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by pratyushmp** [comment]
@Borahb There is a merge conflict, please resolve it.

**Comment by Borahb** [comment]
@pratyushmp It is working fine in my system. It shows no issues.

**Comment by SapinderSingh** [comment]
> @pratyushmp It is working fine in my system. It shows no issues.

Merge conflicts can not be on your system. The branch is having merge conflicts. You have to pull the new code, merge it in your branch and then push.

**Comment by Borahb** [comment]
@pratyushmp  I have updated my changes in this commit.

**Comment by infiniteoverflow** [comment]
@Borahb Your branch is 8 commits behind the main branch , kindly even it...it will reduce the merge conflicts

**Comment by Borahb** [comment]
@infiniteoverflow How do I even my branch with the main branch.

**Comment by pratyushmp** [comment]
Enter the following commands in the terminal:- 
```
git remote add upstream 'https://github.com/pratyushmp/Batua'

git fetch upstream

git pull upstream main

git push origin <your-branch-name>
```

**Comment by Borahb** [comment]
@pratyushmp  I have resolved the conflicts. Thank you

**Review by pratyushmp — APPROVED** [review]

**Comment by pratyushmp** [comment]
Good Job @Borahb !

**Pull request merged**
